### ISSUE TITLE
Segmentation Fault on grip 0.1.5-beta

### ISSUE THREAD

**Issue by GiovaniFerraroTrivelli** [In-line/grip#150]
```
Program terminated with signal SIGABRT, Aborted.
#0  0xf770bbe9 in __kernel_vsyscall ()
#0  0xf770bbe9 in __kernel_vsyscall ()
#1  0xf747fea9 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf7481407 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0xf1d9ce45 in tokio_threadpool::worker::Worker::sleep_light::h8c2b89afcad56853 () from cstrike/addons/amxmodx/modules/grip_amxx_i386.so
#4  0x00000005 in ?? ()
#5  0xffd8f470 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
No symbol table info available.
```

I am having this problem on multiple servers. I tested with 0.1.3 beta and this problem happens too.

**Comment by GiovaniFerraroTrivelli** [comment]
Here is another stack trace:

```
Program terminated with signal SIGABRT, Aborted.
#0  0xf77ccbe9 in __kernel_vsyscall ()
[Current thread is 1 (Thread 0xf74a9a40 (LWP 15698))]
#0  0xf77ccbe9 in __kernel_vsyscall ()
#1  0xf7540ea9 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf7542407 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0xf757c37c in ?? () from /lib/i386-linux-gnu/libc.so.6
#4  0xf75822f7 in ?? () from /lib/i386-linux-gnu/libc.so.6
#5  0xf7582c31 in ?? () from /lib/i386-linux-gnu/libc.so.6
#6  0xf1bac391 in core::ptr::real_drop_in_place::h0164f50a0c2b59bd () from cstrike/addons/amxmodx/modules/grip_amxx_i386.so
#7  0xf1ba2dac in bacon_rajan_cc::cc_box_ptr::CcBoxPtr::free::hdb134c35017ab469 () from cstrike/addons/amxmodx/modules/grip_amxx_i386.so
#8  0xf1be07eb in grip_process_request () from cstrike/addons/amxmodx/modules/grip_amxx_i386.so
#9  0xf1b985aa in StartFrame() () from cstrike/addons/amxmodx/modules/grip_amxx_i386.so
```
